### ISSUE TITLE
Clearing the terminal screen before a question is printed

### ISSUE THREAD

**Issue by zerefwayne** [zerefwayne/quizgo#5]
Current: The terminal screen doesn't clear when a new question comes up.

Feature Requested: Fix the mentioned bug.

Pointers: Terminal clearing statement depends on the operating system so keep that in mind while fixing the bug.

**Comment by learning-dev** [comment]
@zerefwayne can you assign this to me?

**Comment by zerefwayne** [comment]
@learning-dev Sure! Please go ahead. Also, it would be of a great help if you can star this repo and share the post to show your support.

**Comment by learning-dev** [comment]
@zerefwayne  I have written a method to clear the screen. But it is not being called. I have defined it in utils.go. No Errors either

**Comment by zerefwayne** [comment]
@learning-dev Yeah that was the same problem I was facing. Please push the code to your repo so I can have a look.

**Comment by EnzoAliatis** [comment]
i think that we can use `fmt.Println("\033[2J")` and that's it, for keeping simple
