### ISSUE TITLE
Add navigation in the game flow

### ISSUE THREAD

**Issue by zerefwayne** [zerefwayne/quizgo#7]
Right now, the user has to answer the question on the screen before moving on to the next.

Feature Requested: There should be options to skip back and forth between the questions. Keep in mind the range limit of the question set size.

**Comment by setraj** [comment]
@zerefwayne I would like to work on this.

**Comment by zerefwayne** [comment]
Hi Rajesh,

Before you start working on the feature, it would be better we discuss
about how it should be implemented.

Process I have in mind: When a user is seeing a question, he/she can chose
to go to next question or previous question. This will mean we have to keep
a track of two things:

1. If the question is already answered or not.
2. Let the user select previous/next/answer the question instead of just
giving the option to enter an answer.

**Comment by setraj** [comment]
- We can capture the up/down arrow key. Based on the key, the user can navigate back & forth.

- As soon as the question is answered, we remove it from the cache of questions, so that only unsolved questions are there to be navigated.

**Comment by zerefwayne** [comment]
- The up/down arrow key idea sounds nice. Although it would be better if it can be implemented via left/right I guess. It is more intuitive that way.

- We can keep a track of the questions answered if the user navigates back to the question we can check if the question has already been answered and display the information. This will be better as the user will always see the "question number/total questions" on the screen.

For eg.

```
Question 3/15: 
```

**Comment by setraj** [comment]
> * The up/down arrow key idea sounds nice. Although it would be better if it can be implemented via left/right I guess. It is more intuitive that way.
> * We can keep a track of the questions answered if the user navigates back to the question we can check if the question has already been answered and display the information. This will be better as the user will always see the "question number/total questions" on the screen.
> 
> For eg.
> 
> ```
> Question 3/15: 
> ```

on point 2, are we going to show the answer to the solved questions, during navigations?

**Comment by zerefwayne** [comment]
@setraj Yes we surely can. :+1:

**Comment by setraj** [comment]
finding it a bit tricky to capture both the function key(left, right) and number keys at the same time. 
any suggestions? @EnzoAliatis @zerefwayne @learning-dev
